//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Words_2._2 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ENG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ENG() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game_Words_2._2.ENG", typeof(ENG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game сommands:
        ////show-words – displays all user-entered words in the current game;
        ////score – displays the total game score for current players;
        ////total-score – displays the total score for all players.
        ///Surrender – the end of the game with defeat..
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing the difficulty level
        ///1. Easy (delay between of words 60 sec)
        ///2. Medium (delay between of words 30 sec)
        ///3. Hard (delay between of words 10 sec).
        /// </summary>
        internal static string ComplexityMenu {
            get {
                return ResourceManager.GetString("ComplexityMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complexity level: .
        /// </summary>
        internal static string ComplexityStatus {
            get {
                return ResourceManager.GetString("ComplexityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easy.
        /// </summary>
        internal static string ComplexityStatusEasy {
            get {
                return ResourceManager.GetString("ComplexityStatusEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard.
        /// </summary>
        internal static string ComplexityStatusHard {
            get {
                return ResourceManager.GetString("ComplexityStatusHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium.
        /// </summary>
        internal static string ComplexityStatusMedium {
            get {
                return ResourceManager.GetString("ComplexityStatusMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create game....
        /// </summary>
        internal static string CreateGame {
            get {
                return ResourceManager.GetString("CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End game....
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entered words:.
        /// </summary>
        internal static string EnteredWords {
            get {
                return ResourceManager.GetString("EnteredWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main word: .
        /// </summary>
        internal static string EnterMainWord {
            get {
                return ResourceManager.GetString("EnterMainWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The wrong choice was made!.
        /// </summary>
        internal static string ErrorChoice {
            get {
                return ResourceManager.GetString("ErrorChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gender of player
        ///1. Man
        ///2. Woman.
        /// </summary>
        internal static string GenderMenu {
            get {
                return ResourceManager.GetString("GenderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose your language
        ///1. Russian
        ///2. English
        ///Your choice:  .
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loser: .
        /// </summary>
        internal static string Loser {
            get {
                return ResourceManager.GetString("Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. New game
        ///2. Change number of players
        ///3. Сhange of the complexity
        ///4. Change language
        ///5. Exit.
        /// </summary>
        internal static string MenuInfo {
            get {
                return ResourceManager.GetString("MenuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missis .
        /// </summary>
        internal static string Missis {
            get {
                return ResourceManager.GetString("Missis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mister .
        /// </summary>
        internal static string Mister {
            get {
                return ResourceManager.GetString("Mister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of players: .
        /// </summary>
        internal static string NumberOfPlayers {
            get {
                return ResourceManager.GetString("NumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of players must be greater than 2!.
        /// </summary>
        internal static string NumberOfPlayersError {
            get {
                return ResourceManager.GetString("NumberOfPlayersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of wins: .
        /// </summary>
        internal static string NumberOfWins {
            get {
                return ResourceManager.GetString("NumberOfWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player name: .
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The player name must be between 1 and 30 characters!.
        /// </summary>
        internal static string PlayerNameError {
            get {
                return ResourceManager.GetString("PlayerNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player number .
        /// </summary>
        internal static string PlayerNumber {
            get {
                return ResourceManager.GetString("PlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your choice.
        /// </summary>
        internal static string PointerOfChoice {
            get {
                return ResourceManager.GetString("PointerOfChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rules of the game: at the beginning of the game, the user enters a word with a length of 8 to 30 characters: the essence of the game is that 2 users alternately enter words consisting of the letters of the originally specified word and not shorter than two characters. The player who in turn does not enter the word within 60 seconds loses..
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beginning of game....
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time&apos;s up!.
        /// </summary>
        internal static string StopTime {
            get {
                return ResourceManager.GetString("StopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surrender.
        /// </summary>
        internal static string Surrender {
            get {
                return ResourceManager.GetString("Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your time: .
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game &quot;Words&quot;.
        /// </summary>
        internal static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winers: .
        /// </summary>
        internal static string Winers {
            get {
                return ResourceManager.GetString("Winers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! The entered command does not exist..
        /// </summary>
        internal static string WrongCommandError {
            get {
                return ResourceManager.GetString("WrongCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! The word does not correspond to the main word..
        /// </summary>
        internal static string WrongComplianceError {
            get {
                return ResourceManager.GetString("WrongComplianceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! The word has wrong length..
        /// </summary>
        internal static string WrongLongError {
            get {
                return ResourceManager.GetString("WrongLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! This word has already been introduced earlier..
        /// </summary>
        internal static string WrongRepetitionError {
            get {
                return ResourceManager.GetString("WrongRepetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! The word has wrong symbol..
        /// </summary>
        internal static string WrongSymbolError {
            get {
                return ResourceManager.GetString("WrongSymbolError", resourceCulture);
            }
        }
    }
}
