//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Words_2._2 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game_Words_2._2.RU", typeof(RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровые команды:
        ////show-words – отображает все введенные пользователями слова в текущей игре;
        ////score – отображает общий счет по играм для текущих игроков;
        ////total-score – отображает общий счет для всех игроков.
        ///Сдаюсь – завершение игры с поражением. .
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение уровня сложности
        ///1. Лёгкий (задержка между слов 60 секунд)
        ///2. Средний (задержка между слов 30 секунд)
        ///3. Сложный (задержка между слов 10 секунд).
        /// </summary>
        internal static string ComplexityMenu {
            get {
                return ResourceManager.GetString("ComplexityMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень сложности: .
        /// </summary>
        internal static string ComplexityStatus {
            get {
                return ResourceManager.GetString("ComplexityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лёгкий.
        /// </summary>
        internal static string ComplexityStatusEasy {
            get {
                return ResourceManager.GetString("ComplexityStatusEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сложный.
        /// </summary>
        internal static string ComplexityStatusHard {
            get {
                return ResourceManager.GetString("ComplexityStatusHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний.
        /// </summary>
        internal static string ComplexityStatusMedium {
            get {
                return ResourceManager.GetString("ComplexityStatusMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание игры....
        /// </summary>
        internal static string CreateGame {
            get {
                return ResourceManager.GetString("CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конец игры....
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введённые слова:.
        /// </summary>
        internal static string EnteredWords {
            get {
                return ResourceManager.GetString("EnteredWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главное слово: .
        /// </summary>
        internal static string EnterMainWord {
            get {
                return ResourceManager.GetString("EnterMainWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Был сделан неправильный выбор!.
        /// </summary>
        internal static string ErrorChoice {
            get {
                return ResourceManager.GetString("ErrorChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол игрока
        ///1. Мужской
        ///2. Женский.
        /// </summary>
        internal static string GenderMenu {
            get {
                return ResourceManager.GetString("GenderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите свой язык
        ///1. Русский
        ///2. Английский
        ///Ваш выбор: .
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проигравший: .
        /// </summary>
        internal static string Loser {
            get {
                return ResourceManager.GetString("Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Новая игра
        ///2. Изменить количество игроков
        ///3. Изменить уровень сложности
        ///4. Изменить язык
        ///5. Выход.
        /// </summary>
        internal static string MenuInfo {
            get {
                return ResourceManager.GetString("MenuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Миссис .
        /// </summary>
        internal static string Missis {
            get {
                return ResourceManager.GetString("Missis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мистер .
        /// </summary>
        internal static string Mister {
            get {
                return ResourceManager.GetString("Mister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество игроков: .
        /// </summary>
        internal static string NumberOfPlayers {
            get {
                return ResourceManager.GetString("NumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество игроков должно быть больше 2!.
        /// </summary>
        internal static string NumberOfPlayersError {
            get {
                return ResourceManager.GetString("NumberOfPlayersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество побед: .
        /// </summary>
        internal static string NumberOfWins {
            get {
                return ResourceManager.GetString("NumberOfWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя игрока: .
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя игрока должно быть в интервале от 1 до 30 символов!.
        /// </summary>
        internal static string PlayerNameError {
            get {
                return ResourceManager.GetString("PlayerNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок номер .
        /// </summary>
        internal static string PlayerNumber {
            get {
                return ResourceManager.GetString("PlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш выбор.
        /// </summary>
        internal static string PointerOfChoice {
            get {
                return ResourceManager.GetString("PointerOfChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила игры: в начале игры пользователь вводит слово длинной от 8 до 30 символов: суть игры заключается в том, чтобы 2 пользователя поочередно вводили слова, состоящие из букв первоначально указанного cлова и не короче двух символов. Проигрывает тот, кто в свою очередь не вводит слово в течение 60 секунд..
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало игры....
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время вышло!.
        /// </summary>
        internal static string StopTime {
            get {
                return ResourceManager.GetString("StopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдаюсь.
        /// </summary>
        internal static string Surrender {
            get {
                return ResourceManager.GetString("Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось времени: .
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра &quot;Слова&quot;.
        /// </summary>
        internal static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Победители: .
        /// </summary>
        internal static string Winers {
            get {
                return ResourceManager.GetString("Winers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Введённой команды не существует..
        /// </summary>
        internal static string WrongCommandError {
            get {
                return ResourceManager.GetString("WrongCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Слово не соответствует главному слову..
        /// </summary>
        internal static string WrongComplianceError {
            get {
                return ResourceManager.GetString("WrongComplianceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Слово недопустимой длины..
        /// </summary>
        internal static string WrongLongError {
            get {
                return ResourceManager.GetString("WrongLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Данное слово уже было введено ранее..
        /// </summary>
        internal static string WrongRepetitionError {
            get {
                return ResourceManager.GetString("WrongRepetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! В слове содержатся недопустимые символы..
        /// </summary>
        internal static string WrongSymbolError {
            get {
                return ResourceManager.GetString("WrongSymbolError", resourceCulture);
            }
        }
    }
}
